version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: db
    build:
      context: ../sr_dkr_sql-database
      dockerfile: Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stolenrelations
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - ../sr_dkr_sql-database/backups:/sr-backups
    # - db_data:/var/lib/mysql
    # Only needed if you want to connect from your host machine (e.g., local MySQL client).
    ports:
      - "3306:3306"
    healthcheck: # check the healthiness with the following configuration
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      # interval: 30s
      timeout: 600s
      retries: 20
#   healthcheck:
#     test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD --silent"]
#     interval: 5s
#     timeout: 3s
#     retries: 30
#     start_period: 10s

  adminer:
    image: adminer:latest
    container_name: sr-adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: django-web-container
    volumes:
      - ../:/sr_project_stuff
      - ../DBs:/sr_project_stuff/DBs
      - ../logs:/sr_project_stuff/logs
      - .:/sr_project_stuff/code
    ports:
      - "8000:8000"

    environment:
      - FOO_KEY=bar_val
      - DISA_DJ__ENV_SETTINGS_PATH=config/settings_localdev_env.sh
      - PYTHONPATH=/sr_project_stuff

      # Point Django/app to MySQL service name "db"
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=stolenrelations
      - DB_USER=user
      - DB_PASSWORD=user

    env_file: ./config/settings_localdev_env.sh

    depends_on:
      - db

    ## copies the starting DBs from the git-cloned start-data if necessary
    ## ...then copies the big json files from the git-cloned start-data if necessary
    ## ...then starts a _background_ process to update the big json files
    ## ...then calls runserver.
    command: /bin/bash -c "
      echo 'Waiting for MySQL at db:3306...' \
      && until (echo > /dev/tcp/db/3306) >/dev/null 2>&1; do sleep 1; done \
      && echo 'MySQL is up.' \
      && if test -f ../DBs/dj_disa.sqlite; then echo 'dj_disa.sqlite-file-exists-not-copying'; else cp ../stolen_relations_start_data/dj_disa.db ../DBs/dj_disa.sqlite; fi
      && if test -f ./disa_app/static/data/browse_formatted.json; then echo 'browse_formatted.json-file-exists-not-copying'; else cp ../stolen_relations_start_data/browse_formatted.json ./disa_app/static/data/browse_formatted.json; fi
      && if test -f ./disa_app/static/data/browse.json; then echo 'browse.json-file-exists-not-copying'; else cp ../stolen_relations_start_data/browse.json ./disa_app/static/data/browse.json; fi
      && python disa_app/lib/generate_browse_data_in_background.py 
      && python manage.py runserver 0.0.0.0:8000
      "

volumes:
  db_data:
